---
- name: 'Install command line software'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nmap'
    - 'iftop'
    - 'mtr'
    - 'jmeter'

- name: 'Install GUI applications'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'postman'
    - 'wireshark'
    - 'expressvpn'
    - 'transmission'
