---
- name: 'Import jgkim.atom role'
  include_role:
    name: 'jgkim.atom'

- name: 'Install GUI editors'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'intellij-idea'

- name: 'Copy .vimrc file to the home directory'
  copy:
    src: '.vimrc'
    dest: '~'

- name: 'Install Vundle (Open vim and run :PluginInstall afterwards to install defined plugins)'
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'
