---
- name: 'Install Kubernetes CLI'
  homebrew:
    name: 'kubernetes-cli'
    state: 'installed'
  notify: 'Link kubectl'

- name: 'Install tfenv'
  homebrew:
    name: 'tfenv'
    state: 'installed'
