---
- name: 'Bootstrap development machine'
  hosts: '127.0.0.1'
  connection: 'local'

  handlers:
    - name: 'Reload iTerm2 configuration'
      command: 'defaults read ~/Library/Preferences/com.googlecode.iterm2.plist'

  tasks:
    - name: 'Copy shell bootstrap files to the home directory'
      copy:
        src: 'shell/{{ item }}'
        dest: '~'
      with_items:
        - '.bashrc'
        - '.bash_profile'
        - '.bash_bootstrap'

    - name: 'Ensure fluid project and tooling related bootstrap files are present in the home directory'
      copy:
        src: 'shell/{{ item }}'
        dest: '~'
        force: 'no'
      with_items:
        - '.bash_projects'
        - '.bash_tools'

    - name: 'Ensure ~/bin folder is present'
      file:
        path: '~/bin'
        state: 'directory'

    - name: 'Copy utilities into the ~/bin folder'
      copy:
        src: '{{ item }}'
        dest: '~/bin'
        mode: '0744'
      with_fileglob:
        - 'utils/*'

    - name: 'Install Vundle (Open vim and run :PluginInstall afterwards to install defined plugins)'
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '~/.vim/bundle/Vundle.vim'

    - name: 'Copy .vimrc file to the home directory'
      copy:
        src: 'vim/.vimrc'
        dest: '~'

    - name: 'Install Homebrew packages'
      homebrew:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'bash-completion'
        - 'wget'

    - name: 'Install Homebrew Cask applications'
      homebrew_cask:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'spotify'
        - 'iterm2'

    - name: 'Copy iTerm2 configuration'
      copy:
        src: 'iTerm2/com.googlecode.iterm2.plist'
        dest: '~/Library/Preferences'
      notify:
        - 'Reload iTerm2 configuration'
