---
- name: 'Bootstrap the Mac'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - role: 'apps'
      tags: [ 'apps' ]
    - role: 'engineering'
      tags: ['engineering', 'eng', 'development', 'dev']
    - role: 'git'
      tags: ['git']
    - role: 'mac'
      tags: [ 'mac' ]
    - role: 'photos'
      tags: ['photos']
    - role: 'ssh'
      tags: ['ssh']
    - role: 'terminal'
      tags: ['terminal']
