---
- name: 'Bootstrap development machine'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - 'virtualization'
    - 'browsers'
    - 'editors'
    - 'terminal'

  tasks:
    - name: 'Determine current user'
      command: 'whoami'
      register: 'current_user'
      changed_when: 'False'

    - name: 'Ensure SSH key is available'
      user:
        name: '{{ current_user.stdout }}'
        generate_ssh_key: 'yes'
        ssh_key_bits: '4096'
        ssh_key_file: '~/.ssh/id_rsa'

    - name: 'Ensure base SSH config is available'
      copy:
        src: 'ssh/config'
        dest: '~/.ssh'
        force: 'no'

    - name: 'Install Homebrew packages'
      homebrew:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'bash-completion'
        - 'wget'
        - 'nmap'
        - 'bat'
        - 'unrar'

    - name: 'Install Homebrew Cask applications'
      homebrew_cask:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'spotify'
        - 'postman'
        - 'wireshark'
