---
- name: 'Bootstrap the Mac'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - role: 'git'
      tags: ['git']
    - role: 'terminal'
      tags: ['terminal']
    - role: 'automations'
      tags: ['automations']
    - role: 'software'
      tags: ['software']
    - role: 'ssh'
      tags: ['ssh']
