---
- name: 'Bootstrap development machine'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - role: 'mac'
      tags: [ 'mac' ]
    - role: 'apps'
      tags: [ 'apps' ]
    - role: 'engineering'
      tags: ['engineering', 'eng', 'development', 'dev']
