---
- name: 'Bootstrap development machine'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - 'virtualization'
    - 'browsers'
    - 'editors'
    - 'terminal'
    - 'ssh'
    - 'networking'
    - 'productivity'
