---
- name: 'Bootstrap development machine'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - 'virtualization'
    - 'browsers'
    - 'editors'

  handlers:
    - name: 'Reload iTerm2 configuration'
      command: 'defaults read ~/Library/Preferences/com.googlecode.iterm2.plist'

  tasks:
    - name: 'Determine current user'
      command: 'whoami'
      register: 'current_user'
      changed_when: 'False'

    - name: 'Ensure SSH key is available'
      user:
        name: '{{ current_user.stdout }}'
        generate_ssh_key: 'yes'
        ssh_key_bits: '4096'
        ssh_key_file: '~/.ssh/id_rsa'

    - name: 'Ensure base SSH config is available'
      copy:
        src: 'ssh/config'
        dest: '~/.ssh'
        force: 'no'

    - name: 'Copy shell bootstrap files to the home directory'
      copy:
        src: 'shell/{{ item }}'
        dest: '~'
      with_items:
        - '.bashrc'
        - '.bash_profile'
        - '.bash_bootstrap'

    - name: 'Ensure fluid project and tooling related bootstrap files are present in the home directory'
      copy:
        src: 'shell/{{ item }}'
        dest: '~'
        force: 'no'
      with_items:
        - '.bash_projects'
        - '.bash_tools'

    - name: 'Ensure ~/bin folder is present'
      file:
        path: '~/bin'
        state: 'directory'

    - name: 'Copy utilities into the ~/bin folder'
      copy:
        src: '{{ item }}'
        dest: '~/bin'
        mode: '0744'
      with_fileglob:
        - 'utils/*'

    - name: 'Install Homebrew packages'
      homebrew:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'bash-completion'
        - 'wget'
        - 'nmap'
        - 'bat'
        - 'unrar'

    - name: 'Install Homebrew Cask applications'
      homebrew_cask:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'spotify'
        - 'iterm2'
        - 'postman'
        - 'wireshark'

    - name: 'Copy iTerm2 configuration'
      copy:
        src: 'iTerm2/com.googlecode.iterm2.plist'
        dest: '~/Library/Preferences'
      notify:
        - 'Reload iTerm2 configuration'
