---
- name: 'Bootstrap development machine'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - role: 'mac'
      tags: [ 'mac' ]
    - role: 'apps'
      tags: [ 'apps' ]
    - role: 'terminal'
      tags: ['terminal']
    - role: 'ssh'
      tags: ['ssh']
    - role: 'git'
      tags: ['git']
    - role: 'virtualization'
      tags: ['virtualization']
    - role: 'editors'
      tags: ['editors']
    - role: 'networking'
      tags: ['networking', 'net', 'network']
    - role: 'development-platforms'
      tags: ['development', 'development-platforms', 'dev']
    - role: 'jvm'
      tags: ['java', 'jdk', 'jvm']
    - role: 'cloud'
      tags: ['cloud', 'gcp', 'kubernetes', 'k8s']
