---
- name: 'Bootstrap development machine'
  hosts: '127.0.0.1'
  connection: 'local'

  roles:
    - 'virtualization'
    - 'browsers'
    - 'editors'
    - 'terminal'
    - 'ssh'

  tasks:
    - name: 'Install Homebrew packages'
      homebrew:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'nmap'

    - name: 'Install Homebrew Cask applications'
      homebrew_cask:
        name: '{{ item }}'
        state: 'present'
      with_items:
        - 'spotify'
        - 'postman'
        - 'wireshark'
