---
- name: 'Terminal'
  include_role:
    name: 'terminal'

- name: 'Git'
  include_role:
    name: 'git'

- name: 'SSH'
  include_role:
    name: 'ssh'

- name: 'JVM'
  include_role:
    name: 'jvm'

- name: 'Install GUI editors'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'intellij-idea'

- name: 'Install networking command line software'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nmap'
    - 'iftop'
    - 'jmeter'

- name: 'Install networking apps'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'postman'
    - 'wireshark'

- name: 'Install virtualization software'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'docker'

# Cloud stuff
- name: 'Install Kubernetes CLI'
  homebrew:
    name: 'kubernetes-cli'
    state: 'installed'
  notify: 'Link kubectl'

- name: 'Install tfenv'
  homebrew:
    name: 'tfenv'
    state: 'installed'

# Node.js stuff
- name: 'Install command line tools'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nvm'
    - 'yarn'

- name: 'Ensure NVM working directory is present'
  file:
    path: '~/.nvm'
    state: 'directory'

- name: 'Setup NVM'
  shell: './setup-nvm.sh'
  register: 'nvm_setup'
  changed_when: 'nvm_setup.stdout == "NVM configured"'
