---
- name: 'Install GUI editors'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'intellij-idea'

- name: 'Install networking command line software'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nmap'
    - 'iftop'
    - 'jmeter'

- name: 'Install networking apps'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'postman'
    - 'wireshark'

- name: 'Install virtualization software'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'docker'

# Cloud stuff
- name: 'Install Kubernetes CLI'
  homebrew:
    name: 'kubernetes-cli'
    state: 'installed'
  notify: 'Link kubectl'

- name: 'Install tfenv'
  homebrew:
    name: 'tfenv'
    state: 'installed'

# Node.js stuff
- name: 'Install command line tools for Node.js'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nvm'
    - 'yarn'

- name: 'Ensure NVM working directory is present'
  file:
    path: '~/.nvm'
    state: 'directory'

- name: 'Setup NVM in the shell'
  blockinfile:
    path: '~/.bash_tools'
    marker: '# {mark} ANSIBLE MANAGED NVM CONFIG'
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
      [ -s "/opt/homebrew/opt/nvm/etc/bash_completion" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
    state: 'present'

# JVM stuff
- name: 'Enable Homebrew taps required to setup the JDKs'
  homebrew_tap:
    name: '{{ item }}'
  with_items:
    - 'homebrew/cask-versions'
    - 'shyiko/ktlint'

- name: 'Install the JDK'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'temurin'
    - 'temurin21'

- name: 'Ensure ~/bin folder is present'
  file:
    path: '~/bin'
    state: 'directory'

- name: 'Symlink /usr/libexec/java_home'
  file:
    src: '/usr/libexec/java_home'
    dest: '~/bin/java_home'
    state: 'link'

- name: 'Setup Java in the shell'
  blockinfile:
    path: '~/.bash_tools'
    marker: '# {mark} ANSIBLE MANAGED JVM CONFIG'
    block: |
      export JAVA_HOME=$(/usr/libexec/java_home --version 21)
    state: 'present'

- name: 'Install ktlint'
  homebrew:
    name: 'shyiko/ktlint/ktlint'
    state: 'present'

# Haskell stuff
- name: 'Install GHCup'
  homebrew:
    name: 'ghcup'
    state: 'installed'
