---
- name: 'Terminal'
  include_role:
    name: 'terminal'

- name: 'Git'
  include_role:
    name: 'git'

- name: 'SSH'
  include_role:
    name: 'ssh'

- name: 'Node.js'
  include_role:
    name: 'node'

- name: 'JVM'
  include_role:
    name: 'jvm'

- name: 'Cloud'
  include_role:
    name: 'cloud'

- name: 'Install GUI editors'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'intellij-idea'

- name: 'Install networking command line software'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nmap'
    - 'iftop'
    - 'jmeter'

- name: 'Install networking apps'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'postman'
    - 'wireshark'

- name: 'Install virtualization software'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'docker'
