---
- name: 'Install GUI editors'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'intellij-idea'
    - 'visual-studio-code'

- name: 'Install networking command line software'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nmap'
    - 'iftop'
    - 'jmeter'

- name: 'Install networking apps'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'postman'
    - 'wireshark'

# Node.js stuff
- name: 'Install command line tools for Node.js'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nvm'
    - 'yarn'

- name: 'Ensure NVM working directory is present'
  file:
    path: '~/.nvm'
    state: 'directory'

- name: 'Setup NVM in the shell'
  blockinfile:
    path: '~/.bash_tools'
    marker: '# {mark} ANSIBLE MANAGED NVM CONFIG'
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
      [ -s "/opt/homebrew/opt/nvm/etc/bash_completion" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
    state: 'present'

# JVM stuff
- name: 'Install the JDK'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'temurin'

- name: 'Ensure ~/bin folder is present'
  file:
    path: '~/bin'
    state: 'directory'

- name: 'Symlink /usr/libexec/java_home'
  file:
    src: '/usr/libexec/java_home'
    dest: '~/bin/java_home'
    state: 'link'

- name: 'Setup Java in the shell'
  blockinfile:
    path: '~/.bash_tools'
    marker: '# {mark} ANSIBLE MANAGED JVM CONFIG'
    block: |
      export JAVA_HOME=$(/usr/libexec/java_home)
    state: 'present'
