---
- name: 'Install command line tools'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'imagemagick'

- name: 'Ensure ~/bin folder is present'
  file:
    path: '~/bin'
    state: 'directory'

- name: 'Copy custom CLI utilities into the ~/bin folder'
  copy:
    src: '{{ item }}'
    dest: '~/bin'
    mode: '0744'
  with_fileglob:
    - '*'
