---
- name: 'Enable required Homebrew taps'
  homebrew_tap:
    name: '{{ item }}'
  with_items:
    - 'AdoptOpenJDK/openjdk'
    - 'shyiko/ktlint'

- name: 'Install AdoptOpenJDK/8'
  homebrew_cask:
    name: 'adoptopenjdk8'
    state: 'present'

- name: 'Ensure ~/bin folder is present'
  file:
    path: '~/bin'
    state: 'directory'

- name: 'Symlink /usr/libexec/java_home'
  file:
    src: '/usr/libexec/java_home'
    dest: '~/bin/java_home'
    state: 'link'

- name: 'Copy Java shell configuration'
  copy:
    src: '.bash_jvm'
    dest: '~'

- name: 'Bootstrap Java shell configuration'
  shell: './setup-jvm.sh'
  register: 'jvm_setup'
  changed_when: 'jvm_setup.stdout == "JVM configured"'

- name: 'Install ktlint'
  homebrew:
    name: 'shyiko/ktlint/ktlint'
    state: 'present'
