---
- name: 'Import feffi.macos-computername role'
  include_role:
    name: 'feffi.macos-computername'

- name: 'Ensure Pictures directory is present'
  file:
    path: '~/Pictures'
    state: 'directory'

- name: 'Ensure Projects directory is present'
  file:
    path: '~/Projects'
    state: 'directory'

- name: 'Enable dock auto hiding'
  shell: './macos-configure.sh boolean com.apple.dock autohide true'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart the dock'

- name: 'Set dock tiles size'
  shell: './macos-configure.sh integer com.apple.dock tilesize 48'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart the dock'

- name: 'Enable dock tiles magnification'
  shell: './macos-configure.sh boolean com.apple.dock magnification true'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart the dock'

- name: 'Set dock tiles magnification max size'
  shell: './macos-configure.sh integer com.apple.dock largesize 81'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart the dock'

- name: 'Set window minimize effect'
  shell: './macos-configure.sh string com.apple.dock mineffect scale'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart the dock'

- name: 'Disable recent items in dock'
  shell: './macos-configure.sh boolean com.apple.dock show-recents false'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart the dock'
