---
- name: 'Configure the pull strategy'
  git_config:
    scope: 'global'
    name: 'pull.rebase'
    value: 'true'

- name: 'Add git aliases'
  git_config:
    scope: 'global'
    name: "alias.{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    st: 'status'
    lol: "log --pretty=format:'%C(auto)%h %C(cyan)%ch %C(reset)%s'"
    fix: 'commit --amend --no-edit'
