---
- name: 'Show Battery in menu bar'
  shell: './macos-add-menu-item.sh Battery'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "added"'
  notify: 'Restart SystemUIServer'

- name: 'Show battery percentage'
  shell: './macos-configure.sh string com.apple.menuextra.battery ShowPercent YES'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart SystemUIServer'

- name: 'Show Volume in menu bar'
  shell: './macos-add-menu-item.sh Volume'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "added"'
  notify: 'Restart SystemUIServer'

- name: 'Show Clock in menu bar'
  shell: './macos-add-menu-item.sh Clock'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "added"'
  notify: 'Restart SystemUIServer'

- name: 'Set clock date and time format'
  shell: './macos-configure.sh string com.apple.menuextra.clock DateFormat "EEE d MMM  HH:mm"'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart SystemUIServer'

- name: 'Disable flashing separators'
  shell: './macos-configure.sh boolean com.apple.menuextra.clock FlashDateSeparators false'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart SystemUIServer'

- name: 'Use digital clock display'
  shell: './macos-configure.sh boolean com.apple.menuextra.clock IsAnalog false'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "changed"'
  notify: 'Restart SystemUIServer'

- name: 'Show Bluetooth in menu bar'
  shell: './macos-add-menu-item.sh Bluetooth'
  register: 'entry_update'
  changed_when: 'entry_update.stdout == "added"'
  notify: 'Restart SystemUIServer'
