---
- name: 'Install common utility software'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'shpotify'
    - 'elgato-stream-deck'

- name: 'Ensure "~/bin" folder is present'
  file:
    path: '~/bin'
    state: 'directory'

- name: 'Copy scripts'
  copy:
    src: './bin/'
    mode: '0744'
    dest: '~/bin'

- name: 'Copy Applications'
  copy:
    src: './Applications/'
    mode: '0755'
    dest: '~/Applications'

- name: 'Copy the profile'
  copy:
    src: './profile/'
    mode: '0644'
    dest: '~/Documents'
  notify: 'Install Stream Deck profile'
