#!/bin/bash

for dir in *
do
	if [ -d "$dir" ] && [ -e "$dir/.git" ]
	then
		cd $dir
		echo -e "\033[32mCheckout branch $1 on $dir \033[m"
		eval "git checkout $1"
		echo ""
		echo ""
		cd ..
	fi
done

