#!/bin/bash

pushd () {
	command pushd "$@" > /dev/null
    }

popd () {
	command popd "$@" > /dev/null
}

pushd ~/work

for dir in *
do	
	pushd $dir
	if [[ -d ".git" ]]; then
		remote="$(git remote -v | grep -Eo 'gitlab@defragit\.kainos\.com:.*\.git' | head -1)"
		if [[ -n $remote ]]; then
			new_remote="$(echo $remote | sed -e 's/defragit\.kainos\.com/gitlab\.ruraldev\.org\.uk/g' -e 's/gitlab@/git@/g')"
			echo "Got remote $remote, update to $new_remote"
			eval "git remote set-url origin $new_remote"
		fi
	fi
	popd
done
popd

