#!/bin/bash
#
# Example usage:
#     work-report -d 2015-02-21 coa/*
#
# # #

current_dir="`pwd`"

date_since=""

while getopts "d:" opt; do
	case "$opt" in
		d)
			date_since="$OPTARG"
			;;
		*)
			;;
	esac
done

for dir in "$@"
do
	if [ -d "$dir" ] && [ -e "$dir/.git" ];
	then
		cd "$dir"
		echo -e "\nWork report for $dir"
		git remote -v
		echo ""
		if [ -n "$date_since" ];
		then
			git --no-pager log -p --author="r.lewandowski\|Rafał Lewandowski" --since="$date_since"
		else
			git --no-pager log -p --author="r.lewandowski\|Rafał Lewandowski"
		fi
		cd "$current_dir"
	fi
done

