---
- name: 'Install apps'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'spotify'
    - 'simplediagrams'
    - 'whatsapp'
    - 'slack'
    - 'shiftit'
    - 'flycut'
    - 'vlc'
    - 'telegram'
    - 'google-chrome'
    - 'firefox'
    - 'expressvpn'
    - 'transmission'
    - 'sensiblesidebuttons'
    - 'objektiv'
    - '1password'

- name: 'Install command line stuff'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'exiftool'
