---
- name: 'Install command line tools'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nvm'
    - 'yarn'

- name: 'Ensure NVM working directory is present'
  file:
    path: '~/.nvm'
    state: 'directory'

- name: 'Setup NVM'
  shell: './setup-nvm.sh'
  register: 'nvm_setup'
  changed_when: 'nvm_setup.stdout == "NVM configured"'
