---
- name: 'Install iTerm2 terminal emulator'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'iterm2'

- name: 'Copy iTerm2 configuration'
  copy:
    src: 'iTerm2/com.googlecode.iterm2.plist'
    dest: '~/Library/Preferences'
  notify:
    - 'Reload iTerm2 configuration'

- name: 'Copy shell bootstrap files to the home directory'
  copy:
    src: 'bash/{{ item }}'
    dest: '~'
  with_items:
    - '.bashrc'
    - '.bash_profile'
    - '.bash_bootstrap'

- name: 'Ensure fluid project and tooling related bootstrap files are present in the home directory'
  copy:
    src: 'bash/{{ item }}'
    dest: '~'
    force: 'no'
  with_items:
    - '.bash_projects'
    - '.bash_tools'

- name: 'Ensure ~/bin folder is present'
  file:
    path: '~/bin'
    state: 'directory'

- name: 'Copy utilities into the ~/bin folder'
  copy:
    src: '{{ item }}'
    dest: '~/bin'
    mode: '0744'
  with_fileglob:
    - 'utils/*'
