---
- name: 'Install iTerm2 terminal emulator'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'iterm2'

- name: 'Ensure "~/Library/Application Support/iTerm2/DynamicProfiles" folder is present'
  file:
    path: '~/Library/Application Support/iTerm2/DynamicProfiles'
    state: 'directory'

- name: 'Copy iTerm2 dynamic profiles'
  copy:
    src: 'iTerm2/profiles.json'
    dest: '~/Library/Application Support/iTerm2/DynamicProfiles'

- name: Switch to latest BASH
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/bash
  become: yes

- name: 'Copy shell bootstrap files to the home directory'
  copy:
    src: 'bash/{{ item }}'
    dest: '~'
  with_items:
    - '.bashrc'
    - '.bash_profile'
    - '.bash_bootstrap'

- name: 'Copy .inputrc to the home directory'
  copy:
    src: 'bash/.inputrc'
    dest: '~'

- name: 'Ensure fluid project and tooling related bootstrap files are present in the home directory'
  copy:
    src: 'bash/{{ item }}'
    dest: '~'
    force: 'no'
  with_items:
    - '.bash_projects'
    - '.bash_tools'

- name: 'Ensure ~/bin folder is present'
  file:
    path: '~/bin'
    state: 'directory'

- name: 'Copy custom utility scripts into the ~/bin folder'
  copy:
    src: '{{ item }}'
    dest: '~/bin'
    mode: '0744'
  with_fileglob:
    - 'utils/*'

- name: 'Install common utility software'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'bash-completion'
    - 'wget'
    - 'bat'
    - 'watch'
    - 'pstree'
    - 'jq'
    - 'glances'
    - 'tree'
    - 'coreutils'

- name: 'Install Vundle'
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'
  notify: 'Install Vundle plugins'

- name: 'Copy .vimrc file to the home directory'
  copy:
    src: 'vim/.vimrc'
    dest: '~'
  notify: 'Install Vundle plugins'
